# Generated by Django 4.2.2 on 2023-09-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(default='waiting for confirmation'),
        ),
    ]
